// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: Lexico.jflex

/*
 * Analizador léxico 
 * Brais García Brenlla
 */

package es.udc.InMa.analizador;
import java_cup.runtime.Symbol; 


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\267\u0200\10\u0400\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\0\1\1\22\0\1\1\1\0"+
    "\1\3\13\0\1\4\1\5\12\6\2\0\1\7\1\10"+
    "\1\11\1\12\1\0\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\2\14\1\24\1\25\1\26"+
    "\1\27\1\30\1\14\1\31\1\32\1\33\1\34\1\35"+
    "\1\14\1\36\2\14\6\0\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\2\14\1\24\1\25"+
    "\1\26\1\27\1\30\1\14\1\31\1\32\1\33\1\34"+
    "\1\35\1\14\1\36\2\14\265\0\2\37\115\0\1\40"+
    "\u0380\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\17\0\1\4\13\0\1\5"+
    "\46\0\1\6\5\0\1\7\1\0\1\10\1\0\1\11"+
    "\1\0\1\12\1\0\1\13\1\0\1\14\5\0\1\15"+
    "\1\0\1\16\1\15\11\0\1\17\2\0\1\20\3\0"+
    "\1\21\40\0\1\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[146];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\41\0\102\0\143\0\204\0\245\0\306\0\347"+
    "\0\u0108\0\u0129\0\u014a\0\u016b\0\u018c\0\u01ad\0\u01ce\0\u01ef"+
    "\0\u0210\0\u0231\0\u0252\0\347\0\u0273\0\u0294\0\u02b5\0\u02d6"+
    "\0\u02f7\0\u0318\0\u0339\0\u035a\0\u037b\0\u039c\0\u03bd\0\u0210"+
    "\0\u03de\0\u03ff\0\u0420\0\u0441\0\u0462\0\u0483\0\u04a4\0\u04c5"+
    "\0\u04e6\0\u0507\0\u0528\0\u0549\0\u056a\0\u058b\0\u05ac\0\u05cd"+
    "\0\u05ee\0\u060f\0\u0630\0\u0651\0\u0672\0\u0693\0\u06b4\0\u06d5"+
    "\0\u06f6\0\u0717\0\u0738\0\u0759\0\u077a\0\u079b\0\u07bc\0\u07dd"+
    "\0\u07fe\0\u081f\0\u0840\0\u0861\0\u0882\0\u08a3\0\347\0\u08c4"+
    "\0\u08e5\0\u0906\0\u0927\0\u0948\0\347\0\u0969\0\347\0\u098a"+
    "\0\347\0\u09ab\0\347\0\u09cc\0\347\0\u09ed\0\347\0\u0a0e"+
    "\0\u0a2f\0\u0a50\0\u0a71\0\u0a92\0\347\0\u0ab3\0\347\0\u0ad4"+
    "\0\u0af5\0\u0b16\0\u0b37\0\u0b58\0\u0b79\0\u0b9a\0\u0bbb\0\u0bdc"+
    "\0\u0bfd\0\347\0\u0c1e\0\u0c3f\0\347\0\u0c60\0\u0c81\0\u0ca2"+
    "\0\347\0\u0cc3\0\u0ce4\0\u0d05\0\u0d26\0\u0d47\0\u0d68\0\u0d89"+
    "\0\u0daa\0\u0dcb\0\u0dec\0\u0e0d\0\u0e2e\0\u0e4f\0\u0e70\0\u0e91"+
    "\0\u0eb2\0\u0ed3\0\u0ef4\0\u0f15\0\u0f36\0\u0f57\0\u0f78\0\u0f99"+
    "\0\u0fba\0\u0fdb\0\u0ffc\0\u101d\0\u103e\0\u105f\0\u1080\0\u10a1"+
    "\0\u10c2\0\u0ad4";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[146];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\4\2\1\4\40\2\1\0\32\2\2\3"+
    "\4\2\1\0\31\2\5\0\1\5\4\0\1\6\1\7"+
    "\1\10\1\11\2\10\1\12\2\10\1\13\1\14\3\10"+
    "\1\15\2\10\1\16\1\10\1\17\1\10\1\20\14\0"+
    "\24\21\21\0\1\22\16\0\1\23\2\0\1\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\10\1\24\22\10\1\25"+
    "\5\10\3\0\1\10\1\0\1\10\1\0\1\10\1\24"+
    "\30\10\3\0\1\10\1\0\1\10\1\0\1\10\1\24"+
    "\1\10\1\26\13\10\1\27\12\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\10\1\24\5\10\1\30\22\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\10\1\24\13\10\1\31"+
    "\14\10\3\0\1\10\1\0\1\10\1\0\1\10\1\24"+
    "\5\10\1\32\22\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\10\1\24\15\10\1\33\12\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\10\1\24\5\10\1\34\3\10\1\35"+
    "\13\10\1\35\2\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\10\1\24\11\10\1\36\13\10\1\36\1\10\25\0"+
    "\1\37\13\0\1\21\3\0\1\21\1\0\1\21\1\0"+
    "\1\21\1\40\27\21\26\0\1\41\37\0\1\42\13\0"+
    "\1\10\3\0\1\10\1\0\1\10\1\0\1\10\1\24"+
    "\21\10\1\43\6\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\10\1\24\21\10\1\44\6\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\10\1\24\12\10\1\45\15\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\10\1\24\3\10\1\46"+
    "\24\10\3\0\1\10\1\0\1\10\1\0\1\10\1\24"+
    "\1\10\1\47\26\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\10\1\24\21\10\1\50\6\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\10\1\24\20\10\1\51\5\10\1\51"+
    "\1\10\3\0\1\10\1\0\1\10\1\0\1\10\1\24"+
    "\24\10\1\52\3\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\10\1\24\16\10\1\53\2\10\1\54\6\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\10\1\24\4\10\1\55"+
    "\22\10\13\0\1\56\42\0\1\57\47\0\1\60\14\0"+
    "\1\10\3\0\1\10\1\0\1\10\1\0\1\10\1\24"+
    "\15\10\1\61\12\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\10\1\24\5\10\1\62\22\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\10\1\24\15\10\1\63\12\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\10\1\24\10\10\1\64"+
    "\17\10\3\0\1\10\1\0\1\10\1\0\1\10\1\24"+
    "\7\10\1\65\20\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\10\1\24\17\10\1\66\10\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\10\1\24\11\10\1\67\13\10\1\67"+
    "\2\10\3\0\1\10\1\0\1\10\1\0\1\10\1\24"+
    "\21\10\1\70\6\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\10\1\24\15\10\1\71\12\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\10\1\24\22\10\1\72\5\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\10\1\24\5\10\1\73"+
    "\21\10\21\0\1\74\46\0\1\75\46\0\1\76\3\0"+
    "\1\10\3\0\1\10\1\0\1\10\1\0\1\10\1\24"+
    "\17\10\1\77\10\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\10\1\24\7\10\1\100\20\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\10\1\24\17\10\1\101\10\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\10\1\24\1\10\1\102"+
    "\26\10\3\0\1\10\1\0\1\10\1\0\1\10\1\24"+
    "\5\10\1\103\22\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\10\1\24\1\10\1\104\26\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\10\1\24\3\10\1\105\24\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\10\1\24\15\10\1\106"+
    "\12\10\3\0\1\10\1\0\1\10\1\0\1\10\1\107"+
    "\30\10\3\0\1\10\1\0\1\10\1\0\1\10\1\24"+
    "\12\10\1\110\15\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\10\1\24\15\10\1\111\11\10\17\0\1\112\37\0"+
    "\1\113\41\0\1\114\21\0\1\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\10\1\115\30\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\10\1\24\15\10\1\116\12\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\10\1\117\12\10\1\120"+
    "\15\10\3\0\1\10\1\0\1\10\1\0\1\10\1\121"+
    "\30\10\3\0\1\10\1\0\1\10\1\0\1\10\1\24"+
    "\14\10\1\122\13\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\10\1\123\30\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\10\1\24\11\10\1\124\13\10\1\124\2\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\10\1\125\30\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\10\1\24\15\10\1\126"+
    "\12\10\3\0\1\10\1\0\1\10\1\0\1\10\1\127"+
    "\27\10\26\0\1\130\35\0\1\131\13\0\1\131\32\0"+
    "\1\132\7\0\1\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\10\1\24\17\10\1\133\10\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\10\1\24\5\10\1\134\22\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\10\1\135\30\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\10\1\24\15\10\1\136"+
    "\12\10\3\0\1\10\1\0\1\10\1\0\1\10\1\137"+
    "\27\10\11\0\1\140\55\0\1\141\44\0\1\142\5\0"+
    "\1\142\1\10\3\0\1\10\1\0\1\10\1\0\1\10"+
    "\1\24\11\10\1\143\13\10\1\143\2\10\3\0\1\10"+
    "\1\0\1\10\1\0\1\10\1\24\21\10\1\144\6\10"+
    "\3\0\1\10\1\0\1\10\1\0\1\10\1\24\14\10"+
    "\1\145\12\10\62\0\1\146\42\0\1\147\13\0\1\147"+
    "\1\0\1\10\3\0\1\10\1\0\1\10\1\0\1\10"+
    "\1\24\1\10\1\150\26\10\3\0\1\10\1\0\1\10"+
    "\1\0\1\10\1\24\17\10\1\151\10\10\3\0\1\10"+
    "\1\0\1\10\1\0\1\10\1\152\27\10\10\0\1\153"+
    "\57\0\1\154\11\0\1\10\3\0\1\10\1\0\1\10"+
    "\1\0\1\10\1\155\30\10\3\0\1\10\1\0\1\10"+
    "\1\0\1\10\1\24\1\10\1\156\25\10\3\0\1\157"+
    "\63\0\1\160\12\0\1\10\3\0\1\10\1\0\1\10"+
    "\1\0\1\10\1\161\27\10\1\162\1\0\5\162\1\0"+
    "\1\162\2\0\26\162\10\0\1\163\33\0\1\164\40\0"+
    "\1\165\72\0\1\166\11\0\1\167\51\0\1\170\25\0"+
    "\1\171\1\0\1\167\63\0\1\172\15\0\1\173\64\0"+
    "\1\174\5\0\1\174\3\0\1\175\60\0\1\176\13\0"+
    "\1\176\20\0\1\177\50\0\1\200\37\0\1\201\40\0"+
    "\1\202\27\0\1\203\33\0\1\204\57\0\1\205\14\0"+
    "\1\206\53\0\1\207\30\0\1\210\55\0\1\211\13\0"+
    "\1\211\5\0\1\212\1\0\1\210\60\0\1\213\20\0"+
    "\1\214\53\0\1\215\22\0\1\216\45\0\1\217\42\0"+
    "\1\220\31\0\1\221\46\0\1\222\27\0\1\214\1\0"+
    "\5\214\1\0\1\214\2\0\26\214";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4323];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\1\17\0\1\1\13\0\1\1\46\0\1\1"+
    "\5\0\1\1\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\5\0\1\1\1\0\1\1"+
    "\1\11\11\0\1\1\2\0\1\1\3\0\1\1\40\0"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[146];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new Symbol(sym.TEXTOBASICO, yytext());
            }
            // fall through
          case 18: break;
          case 2:
            { 
            }
            // fall through
          case 19: break;
          case 3:
            { System.out.println("Este es un error lexico: "+yytext()+
    ", en la linea: "+yyline+", en la columna: "+yychar);
            }
            // fall through
          case 20: break;
          case 4:
            { return new Symbol(sym.CAMPO, yytext().split("<")[1]);
            }
            // fall through
          case 21: break;
          case 5:
            { return new Symbol(sym.FINCAMPO, yytext().split("/")[1]);
            }
            // fall through
          case 22: break;
          case 6:
            { return new Symbol(sym.TIPO, yytext().split("<")[1]);
            }
            // fall through
          case 23: break;
          case 7:
            { return new Symbol(sym.AUTOR, yytext().split("<")[1]);
            }
            // fall through
          case 24: break;
          case 8:
            { return new Symbol(sym.COLOR, yytext().split("<")[1]);
            }
            // fall through
          case 25: break;
          case 9:
            { return new Symbol(sym.FECHA, yytext().split("<")[1]);
            }
            // fall through
          case 26: break;
          case 10:
            { return new Symbol(sym.LETRA, yytext().split("<")[1]);
            }
            // fall through
          case 27: break;
          case 11:
            { return new Symbol(sym.TEXTO, yytext().split("<")[1]);
            }
            // fall through
          case 28: break;
          case 12:
            { return new Symbol(sym.VIDEO,yytext().split("<")[1]);
            }
            // fall through
          case 29: break;
          case 13:
            { return new Symbol(sym.IMAGEN,yytext().split("<")[1]);
            }
            // fall through
          case 30: break;
          case 14:
            { return new Symbol(sym.TITULO,yytext().split("<")[1]);
            }
            // fall through
          case 31: break;
          case 15:
            { return new Symbol(sym.POSICION, yytext().split("<")[1]);
            }
            // fall through
          case 32: break;
          case 16:
            { return new Symbol(sym.CATEGORIA,yytext().split("<")[1]);
            }
            // fall through
          case 33: break;
          case 17:
            { return new Symbol(sym.COLORLETRA, yytext().split("<")[1]);
            }
            // fall through
          case 34: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
